// Code generated by protoc-gen-go.
// source: mahjong.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	mahjong.proto

It has these top-level messages:
	LoginReq
	LoginRsp
	CreateTableReq
	CreateTableRsp
	JoinTableReq
	JoinTableRsp
	DrawCardReq
	DrawCardRsp
	HuReq
	HuRsp
	Eat
	EatReq
	EatRsp
	PongReq
	PongRsp
	UserJoinTableMsg
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginReq struct {
	Uid    uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	Passwd string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto1.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginRsp struct {
	ErrCode int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
}

func (m *LoginRsp) Reset()                    { *m = LoginRsp{} }
func (m *LoginRsp) String() string            { return proto1.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()               {}
func (*LoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *LoginRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type CreateTableReq struct {
	Uid uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *CreateTableReq) Reset()                    { *m = CreateTableReq{} }
func (m *CreateTableReq) String() string            { return proto1.CompactTextString(m) }
func (*CreateTableReq) ProtoMessage()               {}
func (*CreateTableReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateTableReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type CreateTableRsp struct {
	ErrCode int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
	TableId uint32 `protobuf:"varint,3,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
}

func (m *CreateTableRsp) Reset()                    { *m = CreateTableRsp{} }
func (m *CreateTableRsp) String() string            { return proto1.CompactTextString(m) }
func (*CreateTableRsp) ProtoMessage()               {}
func (*CreateTableRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateTableRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *CreateTableRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *CreateTableRsp) GetTableId() uint32 {
	if m != nil {
		return m.TableId
	}
	return 0
}

type JoinTableReq struct {
	Uid     uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	TableId uint32 `protobuf:"varint,2,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
}

func (m *JoinTableReq) Reset()                    { *m = JoinTableReq{} }
func (m *JoinTableReq) String() string            { return proto1.CompactTextString(m) }
func (*JoinTableReq) ProtoMessage()               {}
func (*JoinTableReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *JoinTableReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *JoinTableReq) GetTableId() uint32 {
	if m != nil {
		return m.TableId
	}
	return 0
}

type JoinTableRsp struct {
	ErrCode int32  `protobuf:"varint,1,opt,name=err_code,json=errCode" json:"err_code,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"`
}

func (m *JoinTableRsp) Reset()                    { *m = JoinTableRsp{} }
func (m *JoinTableRsp) String() string            { return proto1.CompactTextString(m) }
func (*JoinTableRsp) ProtoMessage()               {}
func (*JoinTableRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *JoinTableRsp) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *JoinTableRsp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type DrawCardReq struct {
	Card uint32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
}

func (m *DrawCardReq) Reset()                    { *m = DrawCardReq{} }
func (m *DrawCardReq) String() string            { return proto1.CompactTextString(m) }
func (*DrawCardReq) ProtoMessage()               {}
func (*DrawCardReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DrawCardReq) GetCard() uint32 {
	if m != nil {
		return m.Card
	}
	return 0
}

type DrawCardRsp struct {
	Card uint32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
}

func (m *DrawCardRsp) Reset()                    { *m = DrawCardRsp{} }
func (m *DrawCardRsp) String() string            { return proto1.CompactTextString(m) }
func (*DrawCardRsp) ProtoMessage()               {}
func (*DrawCardRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DrawCardRsp) GetCard() uint32 {
	if m != nil {
		return m.Card
	}
	return 0
}

type HuReq struct {
	Card uint32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
}

func (m *HuReq) Reset()                    { *m = HuReq{} }
func (m *HuReq) String() string            { return proto1.CompactTextString(m) }
func (*HuReq) ProtoMessage()               {}
func (*HuReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *HuReq) GetCard() uint32 {
	if m != nil {
		return m.Card
	}
	return 0
}

type HuRsp struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *HuRsp) Reset()                    { *m = HuRsp{} }
func (m *HuRsp) String() string            { return proto1.CompactTextString(m) }
func (*HuRsp) ProtoMessage()               {}
func (*HuRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *HuRsp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type Eat struct {
	HandCard []int32 `protobuf:"varint,1,rep,packed,name=hand_card,json=handCard" json:"hand_card,omitempty"`
	WaveCard []int32 `protobuf:"varint,2,rep,packed,name=wave_card,json=waveCard" json:"wave_card,omitempty"`
}

func (m *Eat) Reset()                    { *m = Eat{} }
func (m *Eat) String() string            { return proto1.CompactTextString(m) }
func (*Eat) ProtoMessage()               {}
func (*Eat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Eat) GetHandCard() []int32 {
	if m != nil {
		return m.HandCard
	}
	return nil
}

func (m *Eat) GetWaveCard() []int32 {
	if m != nil {
		return m.WaveCard
	}
	return nil
}

type EatReq struct {
	Eat []*Eat `protobuf:"bytes,1,rep,name=eat" json:"eat,omitempty"`
}

func (m *EatReq) Reset()                    { *m = EatReq{} }
func (m *EatReq) String() string            { return proto1.CompactTextString(m) }
func (*EatReq) ProtoMessage()               {}
func (*EatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *EatReq) GetEat() []*Eat {
	if m != nil {
		return m.Eat
	}
	return nil
}

type EatRsp struct {
	Eat     *Eat  `protobuf:"bytes,1,opt,name=eat" json:"eat,omitempty"`
	DisCard int32 `protobuf:"varint,2,opt,name=dis_card,json=disCard" json:"dis_card,omitempty"`
}

func (m *EatRsp) Reset()                    { *m = EatRsp{} }
func (m *EatRsp) String() string            { return proto1.CompactTextString(m) }
func (*EatRsp) ProtoMessage()               {}
func (*EatRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *EatRsp) GetEat() *Eat {
	if m != nil {
		return m.Eat
	}
	return nil
}

func (m *EatRsp) GetDisCard() int32 {
	if m != nil {
		return m.DisCard
	}
	return 0
}

type PongReq struct {
	Card  int32 `protobuf:"varint,1,opt,name=card" json:"card,omitempty"`
	Count int32 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *PongReq) Reset()                    { *m = PongReq{} }
func (m *PongReq) String() string            { return proto1.CompactTextString(m) }
func (*PongReq) ProtoMessage()               {}
func (*PongReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PongReq) GetCard() int32 {
	if m != nil {
		return m.Card
	}
	return 0
}

func (m *PongReq) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PongRsp struct {
	Count   int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	DisCard int32 `protobuf:"varint,2,opt,name=dis_card,json=disCard" json:"dis_card,omitempty"`
}

func (m *PongRsp) Reset()                    { *m = PongRsp{} }
func (m *PongRsp) String() string            { return proto1.CompactTextString(m) }
func (*PongRsp) ProtoMessage()               {}
func (*PongRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PongRsp) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *PongRsp) GetDisCard() int32 {
	if m != nil {
		return m.DisCard
	}
	return 0
}

type UserJoinTableMsg struct {
	Tid  uint32 `protobuf:"varint,1,opt,name=tid" json:"tid,omitempty"`
	Uid  uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Pos  int32  `protobuf:"varint,4,opt,name=pos" json:"pos,omitempty"`
}

func (m *UserJoinTableMsg) Reset()                    { *m = UserJoinTableMsg{} }
func (m *UserJoinTableMsg) String() string            { return proto1.CompactTextString(m) }
func (*UserJoinTableMsg) ProtoMessage()               {}
func (*UserJoinTableMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *UserJoinTableMsg) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *UserJoinTableMsg) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserJoinTableMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserJoinTableMsg) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func init() {
	proto1.RegisterType((*LoginReq)(nil), "proto.LoginReq")
	proto1.RegisterType((*LoginRsp)(nil), "proto.LoginRsp")
	proto1.RegisterType((*CreateTableReq)(nil), "proto.CreateTableReq")
	proto1.RegisterType((*CreateTableRsp)(nil), "proto.CreateTableRsp")
	proto1.RegisterType((*JoinTableReq)(nil), "proto.JoinTableReq")
	proto1.RegisterType((*JoinTableRsp)(nil), "proto.JoinTableRsp")
	proto1.RegisterType((*DrawCardReq)(nil), "proto.DrawCardReq")
	proto1.RegisterType((*DrawCardRsp)(nil), "proto.DrawCardRsp")
	proto1.RegisterType((*HuReq)(nil), "proto.HuReq")
	proto1.RegisterType((*HuRsp)(nil), "proto.HuRsp")
	proto1.RegisterType((*Eat)(nil), "proto.Eat")
	proto1.RegisterType((*EatReq)(nil), "proto.EatReq")
	proto1.RegisterType((*EatRsp)(nil), "proto.EatRsp")
	proto1.RegisterType((*PongReq)(nil), "proto.PongReq")
	proto1.RegisterType((*PongRsp)(nil), "proto.PongRsp")
	proto1.RegisterType((*UserJoinTableMsg)(nil), "proto.UserJoinTableMsg")
}

func init() { proto1.RegisterFile("mahjong.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xbe, 0xda, 0xec, 0x2c, 0x5d, 0x55, 0x16, 0x62, 0x83, 0x96, 0xc3, 0xe2, 0x03, 0xea,
	0xa9, 0x07, 0x7a, 0x03, 0x09, 0x04, 0xa5, 0x52, 0x41, 0x20, 0x21, 0x0b, 0x6e, 0x48, 0x91, 0x5b,
	0x5b, 0x69, 0x28, 0x8d, 0x8d, 0xed, 0xd2, 0xbf, 0x8f, 0xc6, 0x49, 0x68, 0x83, 0xd2, 0x3d, 0xf4,
	0xd4, 0xe7, 0x79, 0xef, 0xf9, 0x79, 0xa6, 0x13, 0x18, 0xed, 0xf8, 0xe6, 0xa7, 0xaa, 0x8a, 0xa9,
	0x36, 0xca, 0x29, 0x92, 0xf8, 0x1f, 0xba, 0x84, 0xf4, 0xb3, 0x2a, 0xca, 0x8a, 0xc9, 0xdf, 0x64,
	0x0c, 0xd1, 0xbe, 0x14, 0x59, 0x70, 0x1f, 0x4c, 0x62, 0x86, 0x90, 0x3c, 0x81, 0x81, 0xe6, 0xd6,
	0x1e, 0x44, 0x16, 0xde, 0x07, 0x93, 0x2b, 0xd6, 0x9c, 0x08, 0x81, 0xb8, 0xe2, 0x3b, 0x99, 0x45,
	0xbe, 0xea, 0x31, 0x7d, 0xd3, 0xde, 0x64, 0x35, 0x79, 0x0a, 0xa9, 0x34, 0x26, 0x5f, 0x2b, 0x21,
	0xfd, 0x75, 0x09, 0x1b, 0x4a, 0x63, 0xe6, 0x4a, 0x48, 0x72, 0x0b, 0x08, 0xf3, 0x9d, 0x2d, 0xda,
	0x3b, 0xa5, 0x31, 0x5f, 0x6c, 0x41, 0x29, 0xdc, 0xcc, 0x8d, 0xe4, 0x4e, 0x7e, 0xe3, 0xab, 0x5f,
	0xb2, 0xf7, 0x3d, 0x34, 0xef, 0x6a, 0x2e, 0x4b, 0x42, 0x8f, 0x43, 0x7f, 0x5e, 0x0a, 0xdf, 0xc1,
	0x88, 0x0d, 0xfd, 0xf9, 0xa3, 0xa0, 0xaf, 0xe1, 0xd1, 0x27, 0x55, 0x56, 0xe7, 0x9f, 0xd0, 0x31,
	0x87, 0x5d, 0xf3, 0xfb, 0x53, 0xf3, 0x85, 0x53, 0x78, 0x0e, 0xd7, 0x1f, 0x0c, 0x3f, 0xcc, 0xb9,
	0x11, 0x98, 0x4f, 0x20, 0x5e, 0x73, 0x53, 0x3f, 0x60, 0xc4, 0x3c, 0xee, 0x48, 0xac, 0xee, 0x95,
	0xdc, 0x41, 0xb2, 0xdc, 0x9f, 0xf3, 0xdf, 0x7a, 0xd2, 0x6a, 0x72, 0x03, 0xa1, 0xda, 0x7a, 0x2a,
	0x65, 0xa1, 0xda, 0xd2, 0xb7, 0x10, 0x2d, 0xb8, 0x23, 0x77, 0x70, 0xb5, 0xe1, 0x95, 0xc8, 0x1b,
	0x63, 0x34, 0x49, 0x58, 0x8a, 0x05, 0x0c, 0x44, 0xf2, 0xc0, 0xff, 0xc8, 0x9a, 0x0c, 0x6b, 0x12,
	0x0b, 0x48, 0xd2, 0x17, 0x30, 0x58, 0x70, 0x87, 0xb9, 0xcf, 0x20, 0x92, 0xdc, 0x79, 0xf7, 0xf5,
	0x4b, 0xa8, 0x57, 0x6e, 0x8a, 0x1c, 0x96, 0xe9, 0xbb, 0x5a, 0x67, 0xf5, 0x51, 0x17, 0xf4, 0xe8,
	0x70, 0x80, 0xa2, 0xb4, 0x6d, 0x96, 0x1f, 0xa0, 0x28, 0xad, 0x8f, 0x9a, 0xc1, 0xf0, 0xab, 0xaa,
	0x8a, 0xff, 0x7b, 0x4c, 0xea, 0x1e, 0xc9, 0x63, 0x48, 0xd6, 0x6a, 0x5f, 0xb9, 0xc6, 0x56, 0x1f,
	0xe8, 0xab, 0xc6, 0x64, 0xf5, 0x51, 0x10, 0x9c, 0x08, 0x1e, 0x0a, 0xfc, 0x01, 0xe3, 0xef, 0x56,
	0x9a, 0x7f, 0x7f, 0x30, 0x2e, 0xd2, 0x18, 0x22, 0x57, 0xb6, 0xc3, 0x45, 0xd8, 0xee, 0x4b, 0x78,
	0xdc, 0x97, 0x9e, 0x4f, 0x05, 0x55, 0x5a, 0xd9, 0x2c, 0xf6, 0x09, 0x08, 0x57, 0x03, 0xdf, 0xf9,
	0xec, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x6b, 0x48, 0x92, 0xa5, 0x03, 0x00, 0x00,
}
